#version: '3.8'

services:
  # MinIO service - provides S3 compatible object storage
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Abcd1234
      MINIO_DOMAIN: minio
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      minio_network:
        aliases:
          - warehouse.minio

  rest:
    image: tabulario/iceberg-rest:1.6.0
    container_name: iceberg-rest
    networks:
      minio_network:
        aliases:
          - iceberg-rest.minio
    ports:
      - "8181:8181"
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://iceberg/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://192.168.138.15:9000


networks:
  minio_network:
    driver: bridge

volumes:
  minio_data:

